version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'react_reversi'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: reversi-db
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
